[package]
name = "compilation"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = [""]
description = ""
repository = ""
homepage = ""
keywords = ["", ""]
categories = ["", ""]
edition = "2018"

[dependencies]
anyhow = "~1.0"
moose = { path = "../moose" }
petgraph = "~0.5"
