FROM ubuntu:20.04

RUN apt update && apt upgrade -y

# Basic tools
RUN apt install -y build-essential curl wget git gnupg
RUN apt install -y python3 python3-pip python3-venv

# Rust and cargo
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH
RUN wget -q https://static.rust-lang.org/rustup/rustup-init.sh; \
    chmod u+x rustup-init.sh; \
    ./rustup-init.sh -y --no-modify-path --default-toolchain stable; \
    chmod -R a+w $RUSTUP_HOME $CARGO_HOME; \
    rm rustup-init.sh

# watchexec
RUN cargo install watchexec

# MPSPDZ
RUN apt install -y openssl xz-utils
RUN curl -L https://github.com/data61/MP-SPDZ/releases/download/v0.1.9/mp-spdz-0.1.9.tar.xz | tar xJv; \
    mv mp-spdz-0.1.9 /MP-SPDZ; \
    cd /MP-SPDZ; \
    Scripts/tldr.sh

# Dependencies
COPY requirements-dev.txt .
RUN pip3 install -r requirements-dev.txt

WORKDIR /runtime
CMD watchexec -e py -r "sh /runtime/docker/dev/worker.sh"
