[package]
name = "moose-modules"
version = "0.2.1-beta.1"
license = "Apache-2.0"
edition = "2018"
authors = [
    "TF Encrypted Authors <tfencrypted@gmail.com>",
]

[dependencies]
tracing-attributes = "0.1"

