[package]
name = "cli"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = [""]
description = ""
repository = ""
homepage = ""
keywords = ["", ""]
categories = ["", ""]
edition = "2018"

[dependencies]
structopt = "0.3"

[dev-dependencies]
assert_cmd = "1.0"
