version: "3.7"

services:

  inputter0:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - "../..:/worker/moose"

  inputter1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - "../..:/worker/moose"

  outputter:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - "../..:/worker/moose"

  choreographer:
    build:
      context: .
      dockerfile: Dockerfile.choreographer
    volumes:
      - "../..:/worker/moose"
