FROM tfencrypted/runtime-base-worker:latest

# MP-SPDZ
RUN apt install -y openssl xz-utils
RUN curl -L https://github.com/data61/MP-SPDZ/releases/download/v0.1.9/mp-spdz-0.1.9.tar.xz | tar xJv; \
    mv mp-spdz-0.1.9 /MP-SPDZ; \
    cd /MP-SPDZ; \
    Scripts/tldr.sh

# Temporary solutions for installing Elk
ENV PATH="/elk/bin:${PATH}"

# Copy over example files
COPY cluster-spec-worker.yaml main.py ./

CMD python3 main.py --verbose
