version: "3.7"

services:

  inputter0:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - "../../moose:/moose"
      - ".:/example"

  inputter1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - "../../moose:/moose"
      - ".:/example"

  outputter:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - "../../moose:/moose"
      - ".:/example"
