[package]
name = "elk"
version = "0.1.6"
license = "MIT"
edition = "2018"
authors = []

[dependencies]
anyhow = "~1.0"
clap = { version = "~3.1", features = ["derive"] }
moose = { path = "../moose" }
