[package]
name = "elk"
version = "0.2.1-beta.1"
license = "Apache-2.0"
edition = "2018"
authors = [
    "TF Encrypted Authors <tfencrypted@gmail.com>",
]
publish = false

[dependencies]
anyhow = "~1.0"
clap = { version = "~3.1", features = ["derive"] }
moose = { path = "../moose" }
