pre-release-replacements = [
    {file="setup.py", search="version=\"[a-z0-9\\.-]+\"", replace="version=\"{{version}}\"", exactly=1},
]
post-release-replacements = [
    {file="setup.py", search="version=\"[0-9\\.]+\"", replace="version=\"{{next_version}}\"", exactly=1},
]
