FROM tfencrypted/runtime-base-worker:latest

# Copy over example files
COPY cluster-spec.yaml worker.py ./
WORKDIR /moose

CMD watchexec -e py -r "cd /example; python3 worker.py --verbose --name $NAME"
