version: "3.7"

services:

  worker0:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - "../../moose:/moose"
      - ".:/example"
    environment:
      CA_CERT: ./certs/ca.crt
      IDENT_CERT: ./certs/worker0.crt
      IDENT_KEY: ./certs/worker0.key

  worker1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - "../../moose:/moose"
      - ".:/example"
    environment:
      CA_CERT: ./certs/ca.crt
      IDENT_CERT: ./certs/worker1.crt
      IDENT_KEY: ./certs/worker1.key

  worker2:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - "../../moose:/moose"
      - ".:/example"
    environment:
      CA_CERT: ./certs/ca.crt
      IDENT_CERT: ./certs/worker2.crt
      IDENT_KEY: ./certs/worker2.key

  worker3:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - "../../moose:/moose"
      - ".:/example"
    environment:
      CA_CERT: ./certs/ca.crt
      IDENT_CERT: ./certs/worker3.crt
      IDENT_KEY: ./certs/worker3.key

  choreographer:
    build:
      context: .
      dockerfile: Dockerfile.choreographer
    volumes:
      - "../../moose:/moose"
      - ".:/example"
    environment:
      CA_CERT: ./certs/ca.crt
      IDENT_CERT: ./certs/choreographer.crt
      IDENT_KEY: ./certs/choreographer.key
