version: "3.7"

services:

  inputter0:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
        - "../../moose:/moose"
        - ".:/examples/python-functions"
    environment:
      PORT: 50000

  inputter1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
        - "../../moose:/moose"
        - ".:/examples/python-functions"
    environment:
      PORT: 50001

  aggregator:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
        - "../../moose:/moose"
        - ".:/examples/python-functions"
    environment:
      PORT: 50002

  outputter:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
        - "../../moose:/moose"
        - ".:/examples/python-functions"
    environment:
      PORT: 50003
