version: "3.7"

services:

  inputter0:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - "../../moose:/moose"
      - ".:/example"
    environment:
      NAME: inputter0

  inputter1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - "../../moose:/moose"
      - ".:/example"
    environment:
      NAME: inputter1

  aggregator:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - "../../moose:/moose"
      - ".:/example"
    environment:
      NAME: aggregator

  outputter:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - "../../moose:/moose"
      - ".:/example"
    environment:
      NAME: outputter

  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.coordinator
    volumes:
      - "../../moose:/moose"
      - ".:/example"
    environment:
      NAME: coordinator
      CA_CERT: ./certs/ca.crt
      IDENT_CERT: ./certs/coordinator.crt
      IDENT_KEY: ./certs/coordinator.key
