version: "3.7"

services:

  inputter0:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
        - "../../moose:/moose"
        - ".:/examples/python-functions"
    environment:
      NAME: inputter0

  inputter1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
        - "../../moose:/moose"
        - ".:/examples/python-functions"
    environment:
      NAME: inputter1

  aggregator:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
        - "../../moose:/moose"
        - ".:/examples/python-functions"
    environment:
      NAME: aggregator

  outputter:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
        - "../../moose:/moose"
        - ".:/examples/python-functions"
    environment:
      NAME: outputter
