name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ubuntu-ci:
    runs-on: self-hosted
    timeout-minutes: 35
    strategy:
      matrix:
        python-version: [3.8.5]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}.
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Rust.
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: Swatinem/rust-cache@v1

      - name: Install OpenBLAS.
        run: |
          sudo apt install libopenblas-dev

      - name: Install OpenSSL.
        run: |
          sudo apt install libssl-dev

      - name: Create virtual environment.
        run: |
          python -m venv venv

      - name: Install dependencies.
        run: |
          . venv/bin/activate
          make pydep

      - name: Install runtime package.
        run: |
          . venv/bin/activate
          make pylib

      - name: Lint check the runtime package.
        run: |
          . venv/bin/activate
          make lint

      - name: Test the runtime.
        run: |
          . venv/bin/activate
          make test-ci
