name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  computation-update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.5]
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}.
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Rust.
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install OpenBLAS.
        run: |
          sudo apt install libopenblas-dev
      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          make pydep
          make pylib
          pip install pycape
      - uses: actions/checkout@v2
        name: Checkout coordinator
        with:
          repository: capeprivacy/coordinator
          token: ${{ secrets.PAT }}
          path: coordinator
      - name: Update computations
        run: |
          . venv/bin/activate
          python coordinator/computations/linear_regression.py \
            --coordinator https://demo.capeprivacy.com \
            --token ${{ secrets.DEMO_TOKEN }} \
            --runtime-version main#${{ github.sha }}
          python coordinator/computations/linear_regression.py \
            --coordinator https://app.capeprivacy.com \
            --token ${{ secrets.PROD_TOKEN }} \
            --runtime-version main#${{ github.sha }}
